^cOriginal Crimson2 source by:
^C============================

              ^wCryogen                      ^g[cryogen@unix.infoserve.net]
           ^cHead Coder Dude                      ^g[rhaksi@vcn.bc.ca]
                                                    ^baka Ryan Haksi

              ^wCorbin                       ^g[wi961@freenet.victoria.bc.ca]
        ^cRuntime Compiler Guru                     ^baka Cam Lesiuk

^CNOTE: No, this is not based on the dikuMUD source, so I dont have to credit 
  those other guys! *grin*^V

