NOTE: Please report connection problems to cryogen@infoserve.net
      I also recommend using a mud client or a decent network terminal package
      refer to the mud web page at http://phantom.me.uvic.ca/mud

^P                     ___
^P       __________   / _/                __               __________
^p       \       _/__/ /__/\ _____/\/\ _ / /_ /\___/\  /\ _\_       /
^p       /______|   / /  /O_) /\ /    \  \ \ //\\ /  \/ /    |______\
^p            A |___\ \ /  \ / // /\/\ \ / /_\\/// /\  /_____| Server
^P                   \/ \/\/ \/ \/    \/ \/   \/ \/  \/ ^p2  
^C
^C                                   The Year is:
^C                                       __    _____  __    __
^c    Mankind has reached               /  \  | __  |/  \  /  \
^c      for the Stars,                 |_/\ | |/ / /| O  || O  |
^c                                       / /   / /   \   | \   |  _    _
^C        And the Anomaly               / /   | |     |  |  |  | /o\  | \
^C          has been discovered...     / /_   | |    /  /  /  / | _ | |O |
^b                                    |____|  |__\  |__/  |__/  |/ \| |_/
^b
^G(PS: Please email suggestions/comments/bugs to ^gcryogen@infoserve.net^G)
^b
