// ****************************************************************************
// Copyright (C) B. Cameron Lesiuk, 1999. All rights reserved.
// Permission to use/copy this code is granted for non-commercial use only.
// B. Cameron Lesiuk
// Victoria, BC, Canada
// wi961@freenet.victoria.bc.ca
// ****************************************************************************
/* This header file is the **ONLY** place to put version information!!! */

#define MOLE_CLIENT_VERSION 0x0132  // hi=major version lo=minor version
#define MOLE_CLIENT_VERSION_TEXT "Version 1.50 (c) B. Cameron Lesiuk 1998"
	/* Misc Version information used - where constants are req'd. */
#define MOLE_CLIENT_VERSION_INFO1 "1.50\000\000" // version data
#define MOLE_CLIENT_VERSION_INFO2 "MOLE Version 1.59\r(c) B. Cameron Lesiuk 1997,1999"

